steps:
  # - name: node:16
  #   entrypoint: yarn
  #   args:
  #     - install
  # - name: node:16
  #   entrypoint: yarn
  #   args:
  #     - test
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - push

  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/todolist
      - back-sha256-1=asia.gcr.io/todolist-361909/back:0.0.7
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-todolist
